### ISSUE TITLE
Plugin reporting compatibility only up to WP5.3

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/page-optimize#38]
The [readme.txt](https://plugins.svn.wordpress.org/page-optimize/tags/0.4.6/readme.txt) on the 0.4.6 branch shows tested up to 5.3, but it's confirmed tested up to 5.4 in the [plugin readme.txt](https://github.com/Automattic/page-optimize/blob/master/readme.txt).

This is causing an incorrect message to appear for anyone who views the plugin details on a site running WP 5.4 (like AT sites).

<img width="780" alt="Screen Shot 2020-04-26 at 11 54 10" src="https://user-images.githubusercontent.com/7596032/80312723-c3f99c00-87b4-11ea-98ea-0cf88a423ecc.png">

It was noticed by a user during 20601812-hc

**Comment by brandonpayton** [comment]
This was was fixed in 8ffb3e397e7383c72894a598dc65f9a65b565fd5 and released as part of 0.4.7. Thanks for the report!
