### ISSUE TITLE
Not all CSS is minified

### ISSUE THREAD

**Issue by tijosh** [Automattic/page-optimize#41]
The static file generated by the plugin contains a mix of minified and un-minified CSS:

![Screenshot](https://d.pr/i/xLupK2+)

On my test site, there is a substantial amount not minified, particularly the theme's original stylesheet (Shoreditch, WPcom theme). 

Context: #2984306-zen

**Comment by aidvu** [comment]
Hey @tijosh,

CSS minification is [disabled by default]( https://github.com/Automattic/page-optimize/blame/942dec7c4f4946643146e7d957fe1d44585429e8/page-optimize.php#L20). Here's the README section for [enabling it](https://github.com/Automattic/page-optimize/blob/master/readme.txt#L34).

**Comment by aidvu** [comment]
Closing this one.
